<?php

include "html/src/setup_tools.php";
include_once "html/src/display_table_tools.php";
include_once "html/src/alter_tools.php";

use PHPUnit\Framework\TestCase;

class alter_toolsTest extends TestCase
{
    // Tests generated by Copilot (Claude Haiku 4.5)
    // minor changes made by me (Madeleine) to fix errors 
    private $conn;

    protected function setUp(): void {
        $this->conn = config();
    }

    protected function tearDown(): void {
        if ($this->conn) {
            $this->conn->close();
        }
    }

    // Test get_result() - Test that it returns a mysqli_result object
    public function test_get_result_returns_mysqli_result() {
        $_SERVER["REQUEST_METHOD"] = "POST";
        $_GET['tablename'] = 'tutors';
        $_POST['tablename'] = 'tutors';
        
        $result = get_result($this->conn);
        
        $this->assertInstanceOf('mysqli_result', $result, 
            "get_result() should return a mysqli_result object");
    }

    // Test get_result() - Test that result contains expected data
    public function test_get_result_contains_data() {
        $_SERVER["REQUEST_METHOD"] = "POST";
        $_GET['tablename'] = 'tutors';
        $_POST['tablename'] = 'tutors';
        
        $result = get_result($this->conn);
        
        $this->assertGreaterThan(0, $result->num_rows, 
            "Result should contain at least one row from tutors table");
        
        $this->assertGreaterThan(0, $result->field_count, 
            "Result should contain at least one field");
    }

    // Test get_result() - Test that result has correct fields
    public function test_get_result_has_correct_fields() {
        $_SERVER["REQUEST_METHOD"] = "POST";
        $_GET['tablename'] = 'tutors';
        $_POST['tablename'] = 'tutors';
        
        $result = get_result($this->conn);
        
        // Check that the result contains expected field names for tutors table
        $fields = $result->fetch_fields();
        $field_names = array_map(function($field) { return $field->name; }, $fields);
        
        $this->assertContains('tutor_id', $field_names, 
            "Result should contain tutor_id field");
        
    }

    // Test get_result() - Test with different table (classes)
    public function test_get_result_with_different_table() {
        $_SERVER["REQUEST_METHOD"] = "POST";
        $_GET['tablename'] = 'classes';
        $_POST['tablename'] = 'classes';
        
        $result = get_result($this->conn);
        
        $this->assertInstanceOf('mysqli_result', $result);
        $this->assertGreaterThan(0, $result->field_count);
        
    }

    // Test check_boxes() - Test when no checkbox is selected
    public function test_check_boxes_no_selection() {
        $_SERVER["REQUEST_METHOD"] = "POST";
        $_GET['tablename'] = 'tutors';
        $_POST['tablename'] = 'tutors';
        
        // Clear any POST data for checkboxes
        for ($i = 0; $i < 10; $i++) {
            unset($_POST["checkbox$i"]);
        }
        
        $result = get_result($this->conn);
        $res = check_boxes($result, $this->conn);
        
        $this->assertEquals(-2, $res, 
            "check_boxes() should return -2 when no checkbox is selected");
    }

    // Test check_boxes() - Test when exactly one checkbox is selected
    public function test_check_boxes_single_selection() {
        $_SERVER["REQUEST_METHOD"] = "POST";
        $_GET['tablename'] = 'tutors';
        $_POST['tablename'] = 'tutors';
        $_POST['checkbox0'] = 'on'; // Select first row
        
        // Clear other checkboxes
        for ($i = 1; $i < 10; $i++) {
            unset($_POST["checkbox$i"]);
        }
        
        $result = get_result($this->conn);
        $res = check_boxes($result, $this->conn);
        
        $this->assertEquals(0, $res, 
            "check_boxes() should return 0 (the index) when first checkbox is selected");
    }

    // Test check_boxes() - Test when multiple checkboxes are selected
    public function test_check_boxes_multiple_selection() {
        $_SERVER["REQUEST_METHOD"] = "POST";
        $_GET['tablename'] = 'classes';
        $_POST['tablename'] = 'classes';
        $_POST['checkbox0'] = 'on'; // Select first row
        $_POST['checkbox1'] = 'on'; // Select second row
        
        $result = get_result($this->conn);
        $res = check_boxes($result, $this->conn);
        
        $this->assertEquals(-1, $res, 
            "check_boxes() should return -1 when more than one checkbox is selected");
    }

    // Test check_boxes() - Test with different row indices
    public function test_check_boxes_different_index() {
        $_SERVER["REQUEST_METHOD"] = "POST";
        $_GET['tablename'] = 'classes';
        $_POST['tablename'] = 'classes';
        $_POST['checkbox2'] = 'on'; // Select third row
        
        // Clear other checkboxes
        for ($i = 0; $i < 10; $i++) {
            if ($i !== 2) {
                unset($_POST["checkbox$i"]);
            }
        }
        
        $result = get_result($this->conn);
        $res = check_boxes($result, $this->conn);
        
        $this->assertEquals(2, $res, 
            "check_boxes() should return 2 (the index) when third checkbox is selected");
    }

    // Test perform_alter() - Test with valid update data
    public function test_perform_alter_valid_update() {
        $_SERVER["REQUEST_METHOD"] = "POST";
        $_GET['tablename'] = 'tutors';
        $_POST['tablename'] = 'tutors';
        
        
        for ($i = 1; $i < 10; $i++) {
            unset($_POST["checkbox$i"]);
        }
        // First, get a tutor to know what we're updating
        $result = get_result($this->conn);
        $result->data_seek(0);
        $first_tutor = $result->fetch_assoc();
        
        // Set up POST data for updating (simulating form submission)
        $_POST['tutor_id'] = $first_tutor['tutor_id'];
        $_POST['orig_tutor_id'] = $first_tutor['tutor_id'];
        $_POST['tutor_first_name'] = 'Updated Test Name'; // Changed value
        $_POST['submit_btn'] = 'Submit';

        
        // This test checks that perform_alter doesn't throw an error
        // Note: perform_alter exits after execution, so we'll use output buffering
        ob_start();
        try {
            perform_alter($this->conn, false);
        } catch (Exception $e) {
            ob_end_clean();
            $this->fail("perform_alter() threw an exception: " . $e->getMessage());
        }
        ob_end_clean();

        // Verify that the update took place
        $tutor_id = $first_tutor['tutor_id'];
        $stmt = $this->conn->prepare("SELECT tutor_first_name FROM tutors WHERE tutor_id = ?");
        $stmt->bind_param("i", $tutor_id);
        $stmt->execute();
        $result = $stmt->get_result();
        $updated_tutor = $result->fetch_assoc();
        $this->assertEquals('Updated Test Name', $updated_tutor['tutor_first_name']);
    }

    // Test perform_alter() - Test with no changes
    public function test_perform_alter_no_changes() {
        $_SERVER["REQUEST_METHOD"] = "POST";
        $_GET['tablename'] = 'tutors';
        $_POST['tablename'] = 'tutors';
        
        // Get first tutor data
        $result = get_result($this->conn);
        $result->data_seek(0);
        $first_tutor = $result->fetch_assoc();
        
        // Set up POST data with no changes (values match original)
        foreach ($first_tutor as $key => $value) {
            $_POST[$key] = $value;
            $_POST["orig_$key"] = $value;
        }
        $_POST['submit_btn'] = 'Submit';
        
        // perform_alter() should exit early with no changes
        ob_start();
        try {
            perform_alter($this->conn, false);
        } catch (Exception $e) {
            ob_end_clean();
            $this->fail("perform_alter() threw an exception: " . $e->getMessage());
        }
        ob_end_clean();

        // 
    }

    // Test perform_alter() - Test which tries to alter PK
    public function test_perform_alter_PK() {
        $_SERVER["REQUEST_METHOD"] = "POST";
        $_GET['tablename'] = 'classes';
        // clear prev POST data
        unset($_POST);
        $_POST['tablename'] = 'classes';
        
        // get Classes data
        $result = get_result($this->conn);
        $result->data_seek(0);
        $first_class = $result->fetch_assoc();
        
        // Set up POST data to change second PK
        $_POST['class_number'] = $first_class['class_number'];
        $_POST['orig_class_number'] = $first_class['class_number'];
        $_POST['subject_code'] = 'DSC'; // Changed value
        $_POST['submit_btn'] = 'Submit';
        print("DDD");
        print(var_dump($_POST));
        
        // should fail
        perform_alter($this->conn, $doExit = false);
        print("HHHHHH");
        print(var_dump($_SESSION));
        $this->assertTrue(isset($_SESSION['pk_error_msg']),
            "Session variable pk_error_msg should be set when trying to alter PK");
    }

}
?>