<?php
use PHPUnit\Framework\TestCase;

// GENERATED BY COPILOT

class calendar_viewTest extends TestCase
{
    protected function tearDown(): void {
        // Clear global variables for next test
        unset($_GET, $_POST);
    }

    /**
     * Test that htmlspecialchars is applied to subject input
     */
    public function test_input_sanitization() {
        $subject_input = "IT'S A TEST";
        $sanitized = htmlspecialchars($subject_input);
        $this->assertStringContainsString('&#039;', $sanitized);
    }

    /**
     * Test the logic for processing GET parameters when subject is provided
     */
    public function test_subject_provided_parameters() {
        // Simulate: subject is provided, class is not
        $_GET = ['subject' => 'MAT'];
        
        // Replicate the logic from calendar_view.php
        if (isset($_GET['subject']) && !empty($_GET['subject'])) {
            $subject = htmlspecialchars($_GET['subject']);
            $allsubjects = 0;
            if (isset($_GET['class']) && !empty($_GET['class'])) {
                $class = (int)htmlspecialchars($_GET['class']);
                $allclasses = 0;
            } else {
                $class = 0;
                $allclasses = 1;
            }
        } else {
            $subject = '';
            $class = 0;
            $allsubjects = 1;
            $allclasses = 1;
        }

        // Assert the correct values are set
        $this->assertEquals('MAT', $subject);
        $this->assertEquals(0, $class);
        $this->assertEquals(0, $allsubjects);
        $this->assertEquals(1, $allclasses);
    }

    /**
     * Test the logic when both subject and class are provided
     */
    public function test_subject_and_class_provided() {
        $_GET = ['subject' => 'HIS', 'class' => '110'];
        
        if (isset($_GET['subject']) && !empty($_GET['subject'])) {
            $subject = htmlspecialchars($_GET['subject']);
            $allsubjects = 0;
            if (isset($_GET['class']) && !empty($_GET['class'])) {
                $class = (int)htmlspecialchars($_GET['class']);
                $allclasses = 0;
            } else {
                $class = 0;
                $allclasses = 1;
            }
        } else {
            $subject = '';
            $class = 0;
            $allsubjects = 1;
            $allclasses = 1;
        }

        $this->assertEquals('HIS', $subject);
        $this->assertEquals(110, $class);
        $this->assertEquals(0, $allsubjects);
        $this->assertEquals(0, $allclasses);
    }

    /**
     * Test the logic when no parameters are provided
     */
    public function test_no_parameters_provided() {
        $_GET = [];
        
        if (isset($_GET['subject']) && !empty($_GET['subject'])) {
            $subject = htmlspecialchars($_GET['subject']);
            $allsubjects = 0;
            if (isset($_GET['class']) && !empty($_GET['class'])) {
                $class = (int)htmlspecialchars($_GET['class']);
                $allclasses = 0;
            } else {
                $class = 0;
                $allclasses = 1;
            }
        } else {
            $subject = '';
            $class = 0;
            $allsubjects = 1;
            $allclasses = 1;
        }

        $this->assertEquals('', $subject);
        $this->assertEquals(0, $class);
        $this->assertEquals(1, $allsubjects);
        $this->assertEquals(1, $allclasses);
    }

    /**
     * Test class parameter is cast to integer
     */
    public function test_class_cast_to_integer() {
        $_GET = ['subject' => 'CSC', 'class' => '330'];
        
        if (isset($_GET['subject']) && !empty($_GET['subject'])) {
            $subject = htmlspecialchars($_GET['subject']);
            $allsubjects = 0;
            if (isset($_GET['class']) && !empty($_GET['class'])) {
                $class = (int)htmlspecialchars($_GET['class']);
                $allclasses = 0;
            } else {
                $class = 0;
                $allclasses = 1;
            }
        } else {
            $subject = '';
            $class = 0;
            $allsubjects = 1;
            $allclasses = 1;
        }

        // Assert class is stored as integer
        $this->assertIsInt($class);
        $this->assertEquals(330, $class);
    }

    /**
     * Test stored procedure query generation with all parameters
     */
    public function test_query_generation_with_parameters() {
        $_GET = ['subject' => 'MAT', 'class' => '101'];
        
        if (isset($_GET['subject']) && !empty($_GET['subject'])) {
            $subject = htmlspecialchars($_GET['subject']);
            $allsubjects = 0;
            if (isset($_GET['class']) && !empty($_GET['class'])) {
                $class = (int)htmlspecialchars($_GET['class']);
                $allclasses = 0;
            } else {
                $class = 0;
                $allclasses = 1;
            }
        } else {
            $subject = '';
            $class = 0;
            $allsubjects = 1;
            $allclasses = 1;
        }
        
        $query = "CALL calendar_pivot_view('$subject', '$class', '$allsubjects', '$allclasses')";

        // Verify query structure
        $this->assertStringContainsString('CALL calendar_pivot_view', $query);
        $this->assertStringContainsString('MAT', $query);
        $this->assertStringContainsString('101', $query);
    }

    /**
     * Test stored procedure query generation with defaults
     */
    public function test_query_generation_with_defaults() {
        $_GET = [];
        
        if (isset($_GET['subject']) && !empty($_GET['subject'])) {
            $subject = htmlspecialchars($_GET['subject']);
            $allsubjects = 0;
            if (isset($_GET['class']) && !empty($_GET['class'])) {
                $class = (int)htmlspecialchars($_GET['class']);
                $allclasses = 0;
            } else {
                $class = 0;
                $allclasses = 1;
            }
        } else {
            $subject = '';
            $class = 0;
            $allsubjects = 1;
            $allclasses = 1;
        }
        
        $query = "CALL calendar_pivot_view('$subject', '$class', '$allsubjects', '$allclasses')";

        // Verify query with default values
        $this->assertStringContainsString("CALL calendar_pivot_view('', '0', '1', '1')", $query);
    }

    /**
     * Test empty string subject is treated as no subject
     */
    public function test_empty_subject_treated_as_no_subject() {
        $_GET = ['subject' => '', 'class' => '101'];
        
        if (isset($_GET['subject']) && !empty($_GET['subject'])) {
            $subject = htmlspecialchars($_GET['subject']);
            $allsubjects = 0;
        } else {
            $subject = '';
            $allsubjects = 1;
        }

        // Empty string should not satisfy !empty() check
        $this->assertEquals('', $subject);
        $this->assertEquals(1, $allsubjects);
    }

    /**
     * Test class with non-numeric string is cast to 0
     */
    public function test_non_numeric_class_cast_to_zero() {
        $_GET = ['subject' => 'CSC', 'class' => 'abc'];
        
        if (isset($_GET['subject']) && !empty($_GET['subject'])) {
            $subject = htmlspecialchars($_GET['subject']);
            if (isset($_GET['class']) && !empty($_GET['class'])) {
                $class = (int)htmlspecialchars($_GET['class']);
            } else {
                $class = 0;
            }
        } else {
            $class = 0;
        }

        // Non-numeric string cast to int should be 0
        $this->assertEquals(0, $class);
    }

    /**
     * Test special characters in subject are escaped
     */
    public function test_special_characters_escaped() {
        $_GET = ['subject' => '<script>alert("xss")</script>'];
        
        if (isset($_GET['subject']) && !empty($_GET['subject'])) {
            $subject = htmlspecialchars($_GET['subject']);
        } else {
            $subject = '';
        }

        // Should contain escaped version
        $this->assertStringNotContainsString('<script>', $subject);
        $this->assertStringContainsString('&lt;script&gt;', $subject);
    }
}
