<?php
//All code below generated by Gemini AI

// Assume necessary project tools are included, mimicking File 3's structure
require_once __DIR__ . '/../src/setup_tools.php';
require_once __DIR__ . '/../src/display_table_tools.php';
require_once __DIR__ . '/../src/display_views_tools.php';

use PHPUnit\Framework\TestCase;

// --- Mocks to isolate the test from the actual database/environment ---

// Mock database connection/result to prevent actual execution and capture query
class MockDBConnection_Calendar {
    public $executed_query = '';
    public function query($query) {
        $this->executed_query = $query;
        return new MockDBResult_Calendar();
    }
    public function close() {}
}

class MockDBResult_Calendar {
    public function free() {}
}

// Mock external functions used by the script
function start_view_capture() {}
function finish_view_capture_and_render($conn, $a, $b) {}
function error_checking() {}
function format_result_as_calendar($result) {}

// Override the config function globally for the test environment
function config() {
    global $mock_conn_instance;
    return $mock_conn_instance;
}
// ---------------------------------------------------------------------

class calendar_viewTest extends TestCase
{
    private static $conn;
    protected $mock_conn_instance;

    protected function setUp(): void {
        global $mock_conn_instance;
        $mock_conn_instance = new MockDBConnection_Calendar();
    }
    
    protected function tearDown(): void {
        // Clear global variables for next test
        unset($_GET, $_POST);
    }

    /**
     * Helper function to run the view script and return the captured query
     */
    private function run_view_script_and_get_query($get_params = [], $post_params = []) {
        global $mock_conn_instance;
        
        $_GET = $get_params;
        $_POST = $post_params;

        ob_start();
        // Include the actual file under test
        include __DIR__ . '/../src/calendar_view.php';
        ob_get_clean(); // Discard HTML output

        // Return the query captured by the mock connection
        return $mock_conn_instance->executed_query;
    }

    /**
     * Test that the page renders the subject selection form
     */
    public function test_page_renders_form() {
        ob_start();
        $_GET = [];
        include __DIR__ . '/../src/calendar_view.php';
        $output = ob_get_clean();

        $this->assertStringContainsString('<form action="calendar_view.php" method="POST">', $output);
        $this->assertStringContainsString('name="subject"', $output);
        $this->assertStringContainsString('name="class"', $output);
    }

    /**
     * Test default view with no parameters (Should query for all subjects/classes)
     */
    public function test_no_parameters_defaults_to_all() {
        $executed_query = $this->run_view_script_and_get_query([], []);
        // Expects the query to use default 'all' flags (1, 1) and empty subject/class
        $this->assertStringContainsString("CALL calendar_pivot_view('', '0', '1', '1')", $executed_query);
    }

    /**
     * Test with 'subject' provided in GET
     */
    public function test_get_subject_only() {
        $executed_query = $this->run_view_script_and_get_query(['subject' => 'MAT']);
        // Expects 'all subjects' flag to be 0, 'all classes' flag to be 1
        $this->assertStringContainsString("CALL calendar_pivot_view('MAT', '0', '0', '1')", $executed_query);
    }

    /**
     * Test with 'subject' and 'class' provided in GET
     */
    public function test_get_subject_and_class() {
        $executed_query = $this->run_view_script_and_get_query(['subject' => 'HIS', 'class' => '110']);
        // Expects both 'all' flags to be 0, specific values used
        $this->assertStringContainsString("CALL calendar_pivot_view('HIS', '110', '0', '0')", $executed_query);
    }

    /**
     * Test that input sanitization (htmlspecialchars) is applied
     */
    public function test_input_sanitization() {
        // Test that special characters are handled and passed into the query string safely
        $subject_input = "IT'S A TEST";
        $executed_query = $this->run_view_script_and_get_query(['subject' => $subject_input]);
        
        // PHP's htmlspecialchars makes the string safe *for HTML output*, but the raw string 
        // (which still contains the single quote) is what is passed to the database procedure call string.
        // We rely on the database procedure's prepared statement within File 2 to handle the actual safety.
        $this->assertStringContainsString("CALL calendar_pivot_view('IT&#039;S A TEST', '0', '0', '1')", $executed_query);
    }
}
Use code with caution.

Test for File 2: calendar_pivot_view
Since File 2 is a stored procedure, testing it requires direct SQL commands. This uses the style of SQL comments found in the original file.
Save this as tests/test_calendar_pivot_view.sql:
sql
-- SQL Script to perform integration/unit tests on the calendar_pivot_view stored procedure.
-- This script requires existing tables (slots, time_blocks) in the 'clc_tutoring' schema.

USE clc_tutoring;

-- -------------------------------------------------------------
-- Setup Phase: Prepare the environment and insert test data
-- -------------------------------------------------------------

-- Note: The procedure uses CURRENT_DATE() to determine the current term/year.
-- The test data below assumes the script is run when CURRENT_DATE() falls within 
-- the 'FA' term (e.g., sometime between August and December of the current year).

SET @current_year = YEAR(CURRENT_DATE());
SET @term = 'FA';

-- Clean up previous test data if the script ran before
DELETE FROM slots WHERE subject_code IN ('TST', 'CS');
DELETE FROM time_blocks WHERE time_block_id BETWEEN 900 AND 999;

-- Insert mock time blocks
INSERT INTO time_blocks (time_block_id, week_day_name, time_block_start, time_block_end) VALUES
(999, 'M', '10:00:00', '11:00:00'),
(998, 'W', '10:00:00', '11:00:00'),
(997, 'T', '13:00:00', '14:00:00');

-- Insert mock slots data for the *current* term/year
INSERT INTO slots (subject_code, class_number, term_code, year_term_year, time_block_id, building_name, place_room_number) VALUES
('TST', 101, @term, @current_year, 999, 'BLDG_A', '101'), -- Mon TST 101
('TST', 101, @term, @current_year, 998, 'BLDG_A', '101'), -- Wed TST 101
('CS', 202,  @term, @current_year, 999, 'BLDG_B', '202'),  -- Mon CS 202
('CS', 202,  @term, @current_year, 997, 'BLDG_B', '202');  -- Tue CS 202

-- -------------------------------------------------------------
-- Test Phase: Execute the procedure and verify output
-- -------------------------------------------------------------

-- TEST CASE 1: All Subjects, All Classes (default behavior)
-- Expected: TST 101 (M, W) and CS 202 (M, T) entries in the respective day columns.
SELECT '--- TEST 1: All Subjects, All Classes ---' AS TEST_DESCRIPTION;
CALL calendar_pivot_view(NULL, NULL, TRUE, TRUE);

-- TEST CASE 2: Specific Subject 'TST', All Classes
-- Expected: Only TST 101 entries (M, W).
SELECT '--- TEST 2: Specific Subject TST, All Classes ---' AS TEST_DESCRIPTION;
CALL calendar_pivot_view('TST', NULL, FALSE, TRUE);

-- TEST CASE 3: Specific Subject 'CS', Specific Class '202'
-- Expected: Only CS 202 entries (M, T).
SELECT '--- TEST 3: Specific Subject CS, Specific Class 202 ---' AS TEST_DESCRIPTION;
CALL calendar_pivot_view('CS', 202, FALSE, FALSE);

-- TEST CASE 4: Non-existent Subject 'PHY'
-- Expected: Empty result set.
SELECT '--- TEST 4: Non-existent Subject PHY ---' AS TEST_DESCRIPTION;
CALL calendar_pivot_view('PHY', NULL, FALSE, TRUE);

-- TEST CASE 5: Filtering for a different term/year (which should yield no results with this test data)
-- This tests the `WHERE term_code = ? AND year_term_year = ?` logic indirectly.
-- Expected: Empty result set.
SELECT '--- TEST 5: Different Year (Expected Empty) ---' AS TEST_DESCRIPTION;
-- We must manually manipulate internal logic for this specific test case, as the procedure hardcodes CURRENT_DATE()
-- This test is harder to perform in-line without altering the procedure code, so we rely on the above tests primarily.


-- -------------------------------------------------------------
-- Cleanup Phase: Remove test data
-- -------------------------------------------------------------
DELETE FROM slots WHERE subject_code IN ('TST', 'CS');
DELETE FROM time_blocks WHERE time_block_id BETWEEN 900 AND 999;
