<?php

require_once "html/src/setup_tools.php";
include_once "html/src/delete_tools.php";

use PHPUnit\Framework\TestCase;

class delete_toolsTest extends TestCase
{

    // !-- CODE BELOW GENERATED BY COPILOT -- !

    private $conn;

    protected function setUp(): void {
        $this->conn = config();
    }

    protected function tearDown(): void {
        if ($this->conn) {
            $this->conn->close();
        }
    }

    // Test build_delete_statement()
    public function test_build_delete_statement() {
        $result = $this->conn->query("SELECT * FROM tutors");
        $_GET['tablename'] = 'tutors';

        $actual = build_delete_statement($result, $this->conn);
        
        // Verify it's a valid DELETE statement with the correct table
        $this->assertStringStartsWith("DELETE FROM tutors WHERE", $actual);

        // Verify it has placeholders for all fields
        $this->assertEquals(
            substr_count($actual, "?"),
            mysqli_num_fields($result),
            "Wrong number of parameter placeholders"
        );
    }

    // Test display_session_del_errors() with foreign key error
    public function test_display_session_del_errors_fk() {
        $_SESSION['fk_delete'] = true;
        
        ob_start();
        display_session_del_errors();
        $output = ob_get_clean();
        
        $this->assertStringContainsString('Delete failed due to foreign key constraint', $output);
        $this->assertFalse(isset($_SESSION['fk_delete']), "Session variable not unset after display");
    }


    // Test display_session_del_errors() with other error
    public function test_display_session_del_errors_other() {
        $_SESSION['other_delete_error'] = true;
        
        ob_start();
        display_session_del_errors();
        $output = ob_get_clean();
        
        $this->assertStringContainsString('Delete failed due to an unknown error', $output);
        $this->assertFalse(isset($_SESSION['other_delete_error']), "Session variable not unset after display");
    }


    // Test soft_delete() for tutors table
    public function test_soft_delete_tutors() {
        $_GET['tablename'] = 'tutors';
        
        // Get an existing tutor record
        $result = $this->conn->query("SELECT * FROM tutors WHERE deleted_when IS NULL LIMIT 1");
        if (!$result || $result->num_rows === 0) {
            $this->markTestSkipped("No available tutor records to test with");
            return;
        }
        
        $tutor = $result->fetch_assoc();
        $tutor_id = $tutor['tutor_id'];
        
        // Create row array as it would come from the table display
        $row = ['dummy', $tutor_id];
        
        // Perform soft delete
        soft_delete($row, $this->conn);
        
        // Verify the record was soft deleted (deleted_when is set)
        $result = $this->conn->query("SELECT deleted_when FROM tutors WHERE tutor_id = $tutor_id");
        $deleted_record = $result->fetch_assoc();
        
        $this->assertNotNull($deleted_record['deleted_when'], "Record was not soft deleted");
        
        // Reset the deleted_when field for the test record
        $this->conn->query("UPDATE tutors SET deleted_when = 0 WHERE tutor_id = $tutor_id");
    }

    // Test delete_records() with normal deletion
    public function test_delete_records() {
        $_GET['tablename'] = 'tutors';
        
        // Get an existing tutor record
        $result = $this->conn->query("SELECT * FROM tutors WHERE deleted_when IS NULL LIMIT 1");
        if (!$result || $result->num_rows === 0) {
            $this->markTestSkipped("No available tutor records to test with");
            return;
        }
        
        // Set up POST data to simulate checkbox selection
        $_POST['checkbox0'] = '0';
        
        // Attempt deletion
        delete_records($result, $this->conn);
        
        // Get the tutor_id that was in the result set
        $result->data_seek(0); // Reset result pointer to first row
        $tutor = $result->fetch_assoc();
        $tutor_id = $tutor['tutor_id'];
        
        // Verify record was soft deleted
        $result = $this->conn->query("SELECT deleted_when FROM tutors WHERE tutor_id = $tutor_id");
        $deleted_record = $result->fetch_assoc();
        
        $this->assertNotNull($deleted_record['deleted_when'], "Record was not soft deleted");
        
        // Reset the deleted_when field for the test record
        $this->conn->query("UPDATE tutors SET deleted_when = 0 WHERE tutor_id = $tutor_id");
    }
 
}