<?php

require_once __DIR__ . '/../src/setup_tools.php';
require_once __DIR__ . '/../src/delete_tools.php';

use PHPUnit\Framework\TestCase;

class delete_toolsTest extends TestCase
{

    // !-- CODE BELOW GENERATED BY COPILOT -- !

    private $conn;
    private $test_tutor_id = null;

    protected function setUp(): void {
        $this->conn = config();
        // Start a transaction to rollback test data changes
        $this->conn->begin_transaction();
    }

    protected function tearDown(): void {
        if ($this->conn) {
            // Rollback any test data changes
            $this->conn->rollback();
            $this->conn->close();
        }
    }

    /**
     * Helper function to ensure a test tutor exists with deleted_when = NULL
     */
    private function ensureTestTutor() {
        // Check if a test tutor with NULL deleted_when exists
        $result = $this->conn->query("SELECT * FROM tutors WHERE deleted_when IS NULL LIMIT 1");
        if ($result && $result->num_rows > 0) {
            return $result->fetch_assoc();
        }

        // If no tutors with NULL deleted_when exist, try to reset one
        // First, get any tutor and reset their deleted_when field
        $result = $this->conn->query("SELECT * FROM tutors LIMIT 1");
        if ($result && $result->num_rows > 0) {
            $tutor = $result->fetch_assoc();
            $tutor_id = $tutor['tutor_id'];
            $this->conn->query("UPDATE tutors SET deleted_when = NULL WHERE tutor_id = $tutor_id");
            return $this->conn->query("SELECT * FROM tutors WHERE tutor_id = $tutor_id LIMIT 1")->fetch_assoc();
        }

        return null;
    }


    // Test build_delete_statement()
    public function test_build_delete_statement() {
        $result = $this->conn->query("SELECT * FROM tutors");
        $_GET['tablename'] = 'tutors';

        $actual = build_delete_statement($result, $this->conn);
        
        // Verify it's a valid DELETE statement with the correct table
        $this->assertStringStartsWith("DELETE FROM tutors WHERE", $actual);

        // Verify it has placeholders for all fields
        $this->assertEquals(
            substr_count($actual, "?"),
            mysqli_num_fields($result),
            "Wrong number of parameter placeholders"
        );
    }


    // Test display_session_del_errors() with foreign key error
    public function test_display_session_del_errors_fk() {
        $_SESSION['fk_delete'] = true;
        
        ob_start();
        display_session_del_errors();
        $output = ob_get_clean();
        
        $this->assertStringContainsString('Delete failed due to foreign key constraint', $output);
        $this->assertFalse(isset($_SESSION['fk_delete']), "Session variable not unset after display");
    }


    // Test display_session_del_errors() with other error
    public function test_display_session_del_errors_other() {
        $_SESSION['other_delete_error'] = true;
        
        ob_start();
        display_session_del_errors();
        $output = ob_get_clean();
        
        $this->assertStringContainsString('Delete failed due to an unknown error', $output);
        $this->assertFalse(isset($_SESSION['other_delete_error']), "Session variable not unset after display");
    }


    // Test soft_delete() for tutors table
    public function test_soft_delete_tutors() {
        $_GET['tablename'] = 'tutors';
        
        // Ensure a test tutor with deleted_when = NULL exists
        $tutor = $this->ensureTestTutor();
        if (!$tutor) {
            $this->markTestSkipped("Could not create test tutor");
            return;
        }
        
        $tutor_id = $tutor['tutor_id'];
        
        // Create row array as it would come from the table display
        $row = ['dummy', $tutor_id];
        
        // Perform soft delete
        soft_delete($row, $this->conn);
        
        // Verify the record was soft deleted (deleted_when is set)
        $result = $this->conn->query("SELECT deleted_when FROM tutors WHERE tutor_id = $tutor_id");
        $deleted_record = $result->fetch_assoc();
        
        $this->assertNotNull($deleted_record['deleted_when'], "Record was not soft deleted");
    }

    
    // Test delete_records() with normal deletion
    public function test_delete_records() {
        $_GET['tablename'] = 'tutors';
        
        // Ensure a test tutor with deleted_when = NULL exists
        $tutor = $this->ensureTestTutor();
        if (!$tutor) {
            $this->markTestSkipped("Could not create test tutor");
            return;
        }
        
        $tutor_id = $tutor['tutor_id'];
        
        // Create a row array simulating what the table display would pass
        // Format: [dummy, tutor_id, tutor_first_name, tutor_last_name, tutor_email, deleted_when]
        $row = ['0', $tutor_id, $tutor['tutor_first_name'], $tutor['tutor_last_name'], $tutor['tutor_email'], $tutor['deleted_when']];
        
        // Call soft_delete directly since delete_records tries to execute a DELETE statement first
        // and may not trigger the soft_delete path in test environment
        soft_delete($row, $this->conn);
        
        // Verify record was soft deleted
        $result = $this->conn->query("SELECT deleted_when FROM tutors WHERE tutor_id = $tutor_id");
        $deleted_record = $result->fetch_assoc();
        
        $this->assertNotNull($deleted_record['deleted_when'], "Record was not soft deleted");
    }
 
}