<?php

require_once __DIR__ . '/../src/setup_tools.php';
require_once __DIR__ . '/../src/display_adding_tools.php';
require_once __DIR__ . '/../src/display_table_tools.php';

// GENERATED BY COPILOT 

use PHPUnit\Framework\TestCase;

class display_adding_toolsTest extends TestCase
{
    private $conn;

    protected function setUp(): void {
        $this->conn = config();
        $this->conn->begin_transaction();
    }

    protected function tearDown(): void {
        if ($this->conn) {
            $this->conn->rollback();
            $this->conn->close();
        }
    }

    /**
     * Test get_fields() returns array of field objects
     */
    public function test_get_fields_returns_array() {
        $_GET['tablename'] = 'tutors';
        
        $fields = get_fields($this->conn);
        
        $this->assertIsArray($fields);
        $this->assertNotEmpty($fields);
        $this->assertInstanceOf('stdClass', $fields[0]);
    }

    /**
     * Test get_fields() contains expected field names for tutors table
     */
    public function test_get_fields_contains_expected_fields() {
        $_GET['tablename'] = 'tutors';
        
        $fields = get_fields($this->conn);
        $field_names = array_map(function($field) {
            return $field->name;
        }, $fields);
        
        $this->assertNotEmpty($field_names);
    }

    /**
     * Test display_adding_forms() outputs form HTML
     */
    public function test_display_adding_forms_outputs_form() {
        $_GET['tablename'] = 'tutors';
        $_SESSION['form_values'] = [];
        
        ob_start();
        display_adding_forms($this->conn);
        $output = ob_get_clean();
        
        $this->assertStringContainsString('<form', $output);
        $this->assertStringContainsString('method="POST"', $output);
    }

    /**
     * Test convert_12h_to_24h() converts morning times
     */
    public function test_convert_12h_to_24h_morning() {
        $result = convert_12h_to_24h('9:30 AM');
        
        // Should convert to 24-hour format
        $this->assertNotEmpty($result);
        $this->assertStringContainsString(':', $result);
    }

    /**
     * Test convert_12h_to_24h() converts afternoon times
     */
    public function test_convert_12h_to_24h_afternoon() {
        $result = convert_12h_to_24h('3:45 PM');
        
        // Should convert to 24-hour format
        $this->assertNotEmpty($result);
    }
}
