<?php

require_once __DIR__ . '/../src/setup_tools.php';
require_once __DIR__ . '/../src/display_table_tools.php';

use PHPUnit\Framework\TestCase;

// !! TESTS BELOW GENERATED BY COPILOT !!

class full_schedule_viewTest extends TestCase
{
    private $conn;

    protected function setUp(): void {
        $this->conn = config();
    }

    protected function tearDown(): void {
        if ($this->conn) {
            $this->conn->close();
        }
    }

    /**
     * Test that the page renders the form HTML without errors
     */
    public function test_page_renders_form() {
        ob_start();
        
        // Simulate no GET parameters
        $_GET = [];
        
        // Include the page and capture output
        include __DIR__ . '/../src/full_schedule_view.php';
        $output = ob_get_clean();

        // Assert the form is present
        $this->assertStringContainsString('<form action="full_schedule_view.php" method="GET">', $output);
        $this->assertStringContainsString('Subject code(e.g. HIS, MAT):', $output);
        $this->assertStringContainsString('Class (e.g. 110, 330):', $output);
        $this->assertStringContainsString('<input type="submit" value="See Details"/>', $output);
    }

    /**
     * Test page with no GET parameters (should show all schedules)
     */
    public function test_page_with_no_parameters() {
        ob_start();
        
        $_GET = [];
        
        include __DIR__ . '/../src/full_schedule_view.php';
        $output = ob_get_clean();

        // Should still render the form and table structure
        $this->assertStringContainsString('<form', $output);
        $this->assertStringContainsString('</form>', $output);
    }

    /**
     * Test page with valid subject code
     */
    public function test_page_with_valid_subject() {
        ob_start();
        
        $_GET = ['subject' => 'CSC'];
        
        include __DIR__ . '/../src/full_schedule_view.php';
        $output = ob_get_clean();

        // Should render form and attempt to show schedule
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with subject and class parameters
     */
    public function test_page_with_subject_and_class() {
        ob_start();
        
        $_GET = ['subject' => 'CSC', 'class' => '110'];
        
        include __DIR__ . '/../src/full_schedule_view.php';
        $output = ob_get_clean();

        // Should render form and table
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with invalid subject (HTML special chars)
     */
    public function test_page_with_special_characters_in_subject() {
        ob_start();
        
        $_GET = ['subject' => '<script>'];
        
        try {
            include __DIR__ . '/../src/full_schedule_view.php';
        } catch (\Exception $e) {
            // Catch any exceptions and clean buffer
        }
        $output = ob_get_clean();

        // Should sanitize and render safely (no unescaped script tags in output)
        $this->assertStringNotContainsString('<script>', $output);
        // Form should still be present
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with numeric class parameter
     */
    public function test_page_with_numeric_class() {
        ob_start();
        
        $_GET = ['subject' => 'MAT', 'class' => '330'];
        
        include __DIR__ . '/../src/full_schedule_view.php';
        $output = ob_get_clean();

        // Should render without error
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test that empty subject is treated as null
     */
    public function test_page_with_empty_subject() {
        ob_start();
        
        $_GET = ['subject' => ''];
        
        include __DIR__ . '/../src/full_schedule_view.php';
        $output = ob_get_clean();

        // Should treat as if no subject was provided
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test that non-integer class is cast to integer
     */
    public function test_page_with_non_integer_class() {
        ob_start();
        
        $_GET = ['subject' => 'CSC', 'class' => 'abc123'];
        
        include __DIR__ . '/../src/full_schedule_view.php';
        $output = ob_get_clean();

        // Should handle gracefully (class gets cast to 0)
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test form input field names are correct
     */
    public function test_form_input_field_names() {
        ob_start();
        
        $_GET = [];
        
        include __DIR__ . '/../src/full_schedule_view.php';
        $output = ob_get_clean();

        // Check for correct input field names
        $this->assertStringContainsString('name="subject"', $output);
        $this->assertStringContainsString('name="class"', $output);
    }

    /**
     * Test that the stored procedure call is made with correct default values
     */
    public function test_stored_procedure_defaults() {
        // This test verifies that when no parameters are set,
        // the stored procedure is called with hardcoded semester and year
        
        ob_start();
        
        $_GET = [];
        
        include __DIR__ . '/../src/full_schedule_view.php';
        $output = ob_get_clean();

        // The page should render without fatal errors
        $this->assertIsString($output);
        $this->assertNotEmpty($output);
    }
}