<?php

require_once __DIR__ . '/../src/setup_tools.php';
require_once __DIR__ . '/../src/display_table_tools.php';

use PHPUnit\Framework\TestCase;

// !! TESTS BELOW GENERATED BY COPILOT !!

class full_schedule_viewTest extends TestCase
{
    private $conn;

    protected function setUp(): void {
        $this->conn = config();
    }

    protected function tearDown(): void {
        if ($this->conn) {
            $this->conn->close();
        }
    }

    /**
     * Test that the page renders the form HTML without errors
     */
    public function test_page_renders_form() {
        $_GET = [];
        $_POST = [];
        
        ob_start();
        // Include the page and capture output
        include __DIR__ . '/../src/full_schedule_view.php';
        $output = '';
        while (ob_get_level() > 0) {
            $output = ob_get_clean() . $output;
        }

        // Assert the form is present
        $this->assertStringContainsString('form action="full_schedule_view.php" method="GET"', $output);
        $this->assertStringContainsString('Subject code', $output);
        $this->assertStringContainsString('Class', $output);
        $this->assertStringContainsString('See Details', $output);
    }

    /**
     * Test page with no GET parameters
     */
    public function test_page_with_no_parameters() {
        $_GET = [];
        $_POST = [];
        
        ob_start();
        include __DIR__ . '/../src/full_schedule_view.php';
        $output = '';
        while (ob_get_level() > 0) {
            $output = ob_get_clean() . $output;
        }

        // Should render the form
        $this->assertStringContainsString('form', $output);
    }

    /**
     * Test page with valid subject code
     */
    public function test_page_with_valid_subject() {
        $_GET = ['subject' => 'CSC'];
        $_POST = [];
        
        ob_start();
        include __DIR__ . '/../src/full_schedule_view.php';
        $output = '';
        while (ob_get_level() > 0) {
            $output = ob_get_clean() . $output;
        }

        // Should render form
        $this->assertStringContainsString('form', $output);
    }

    /**
     * Test page with subject and class parameters
     */
    public function test_page_with_subject_and_class() {
        $_GET = ['subject' => 'CSC', 'class' => '110'];
        $_POST = [];
        
        ob_start();
        include __DIR__ . '/../src/full_schedule_view.php';
        $output = '';
        while (ob_get_level() > 0) {
            $output = ob_get_clean() . $output;
        }

        // Should render form
        $this->assertStringContainsString('form', $output);
    }

    /**
     * Test page with numeric class parameter
     */
    public function test_page_with_numeric_class() {
        $_GET = ['subject' => 'MAT', 'class' => '330'];
        $_POST = [];
        
        ob_start();
        include __DIR__ . '/../src/full_schedule_view.php';
        $output = '';
        while (ob_get_level() > 0) {
            $output = ob_get_clean() . $output;
        }

        // Should render without error
        $this->assertStringContainsString('form', $output);
    }

    /**
     * Test that empty subject is treated as null
     */
    public function test_page_with_empty_subject() {
        $_GET = ['subject' => ''];
        $_POST = [];
        
        ob_start();
        include __DIR__ . '/../src/full_schedule_view.php';
        $output = '';
        while (ob_get_level() > 0) {
            $output = ob_get_clean() . $output;
        }

        // Should treat as if no subject was provided
        $this->assertStringContainsString('form', $output);
    }

    /**
     * Test that non-integer class is cast to integer
     */
    public function test_page_with_non_integer_class() {
        $_GET = ['subject' => 'CSC', 'class' => 'abc123'];
        $_POST = [];
        
        ob_start();
        include __DIR__ . '/../src/full_schedule_view.php';
        $output = '';
        while (ob_get_level() > 0) {
            $output = ob_get_clean() . $output;
        }

        // Should handle gracefully
        $this->assertStringContainsString('form', $output);
    }

    /**
     * Test form input field names are correct
     */
    public function test_form_input_field_names() {
        $_GET = [];
        $_POST = [];
        
        ob_start();
        include __DIR__ . '/../src/full_schedule_view.php';
        $output = '';
        while (ob_get_level() > 0) {
            $output = ob_get_clean() . $output;
        }

        // Check for correct input field names
        $this->assertStringContainsString('subject', $output);
        $this->assertStringContainsString('class', $output);
    }

    /**
     * Test that the stored procedure call is made with correct default values
     */
    public function test_stored_procedure_defaults() {
        $_GET = [];
        $_POST = [];
        
        ob_start();
        include __DIR__ . '/../src/full_schedule_view.php';
        $output = '';
        while (ob_get_level() > 0) {
            $output = ob_get_clean() . $output;
        }

        // The page should render without fatal errors
        $this->assertIsString($output);
        $this->assertNotEmpty($output);
    }
}