<?php

require_once __DIR__ . '/../src/setup_tools.php';
require_once __DIR__ . '/../src/display_table_tools.php';

use PHPUnit\Framework\TestCase;

// !! TESTS BELOW GENERATED BY COPILOT !!

class student_history_viewTest extends TestCase
{
    private $conn;

    protected function setUp(): void {
        $this->conn = config();
    }

    protected function tearDown(): void {
        if ($this->conn) {
            $this->conn->close();
        }
    }

    /**
     * Test that the page renders the form HTML without errors
     */
    public function test_page_renders_form() {
        ob_start();
        
        // Simulate no GET parameters
        $_GET = [];
        
        // Include the page and capture output
        include __DIR__ . '/../src/student_history_view.php';
        $output = ob_get_clean();

        // Assert the form is present
        $this->assertStringContainsString('<form action="student_history_view.php" method="GET">', $output);
        $this->assertStringContainsString('First name:', $output);
        $this->assertStringContainsString('Last name:', $output);
        $this->assertStringContainsString('<input type="submit" value="See Details"/>', $output);
    }

    /**
     * Test page with no GET parameters (should show all students)
     */
    public function test_page_with_no_parameters() {
        ob_start();
        
        $_GET = [];
        
        include __DIR__ . '/../src/student_history_view.php';
        $output = ob_get_clean();

        // Should still render the form and table structure
        $this->assertStringContainsString('<form', $output);
        $this->assertStringContainsString('</form>', $output);
    }

    /**
     * Test page with firstname only (should still render without error)
     */
    public function test_page_with_firstname_only() {
        ob_start();
        
        $_GET = ['firstname' => 'John'];
        
        include __DIR__ . '/../src/student_history_view.php';
        $output = ob_get_clean();

        // Should render form (lastname is required for query)
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with lastname only (should still render without error)
     */
    public function test_page_with_lastname_only() {
        ob_start();
        
        $_GET = ['lastname' => 'Doe'];
        
        include __DIR__ . '/../src/student_history_view.php';
        $output = ob_get_clean();

        // Should render form (firstname is required for query)
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with both firstname and lastname
     */
    public function test_page_with_firstname_and_lastname() {
        ob_start();
        
        $_GET = ['firstname' => 'John', 'lastname' => 'Doe'];
        
        include __DIR__ . '/../src/student_history_view.php';
        $output = ob_get_clean();

        // Should render form and table
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with special characters in firstname (HTML injection prevention)
     */
    public function test_page_with_special_characters_in_firstname() {
        ob_start();
        
        $_GET = ['firstname' => '<script>', 'lastname' => 'Test'];
        
        try {
            include __DIR__ . '/../src/student_history_view.php';
        } catch (\Exception $e) {
            // Catch any exceptions and clean buffer
        }
        $output = ob_get_clean();

        // Should sanitize and render safely (no unescaped script tags in output)
        $this->assertStringNotContainsString('<script>', $output);
        // Form should still be present
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with special characters in lastname
     */
    public function test_page_with_special_characters_in_lastname() {
        ob_start();
        
        $_GET = ['firstname' => 'Test', 'lastname' => '<script>'];
        
        try {
            include __DIR__ . '/../src/student_history_view.php';
        } catch (\Exception $e) {
            // Catch any exceptions and clean buffer
        }
        $output = ob_get_clean();

        // Should sanitize and render safely
        $this->assertStringNotContainsString('<script>', $output);
        // Form should still be present
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with empty firstname string
     */
    public function test_page_with_empty_firstname() {
        ob_start();
        
        $_GET = ['firstname' => '', 'lastname' => 'Doe'];
        
        include __DIR__ . '/../src/student_history_view.php';
        $output = ob_get_clean();

        // Should render form (empty strings don't satisfy isset && isset)
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with empty lastname string
     */
    public function test_page_with_empty_lastname() {
        ob_start();
        
        $_GET = ['firstname' => 'John', 'lastname' => ''];
        
        include __DIR__ . '/../src/student_history_view.php';
        $output = ob_get_clean();

        // Should render form (empty strings don't satisfy isset && isset)
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test form input field names are correct
     */
    public function test_form_input_field_names() {
        ob_start();
        
        $_GET = [];
        
        include __DIR__ . '/../src/student_history_view.php';
        $output = ob_get_clean();

        // Check for correct input field names
        $this->assertStringContainsString('name="firstname"', $output);
        $this->assertStringContainsString('name="lastname"', $output);
    }

    /**
     * Test that form method is GET
     */
    public function test_form_method_is_get() {
        ob_start();
        
        $_GET = [];
        
        include __DIR__ . '/../src/student_history_view.php';
        $output = ob_get_clean();

        // Check for GET method
        $this->assertStringContainsString('method="GET"', $output);
    }

    /**
     * Test that stored procedure is called with correct defaults
     */
    public function test_stored_procedure_defaults() {
        // This test verifies that when no parameters are set,
        // the stored procedure is called with NULL values
        
        ob_start();
        
        $_GET = [];
        
        include __DIR__ . '/../src/student_history_view.php';
        $output = ob_get_clean();

        // The page should render without fatal errors
        $this->assertIsString($output);
        $this->assertNotEmpty($output);
    }

    /**
     * Test page with numeric-like string names (valid edge case)
     */
    public function test_page_with_numeric_string_names() {
        ob_start();
        
        $_GET = ['firstname' => '123', 'lastname' => '456'];
        
        include __DIR__ . '/../src/student_history_view.php';
        $output = ob_get_clean();

        // Should handle gracefully
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with very long names (database might have limits)
     */
    public function test_page_with_very_long_names() {
        ob_start();
        
        $_GET = ['firstname' => str_repeat('a', 100), 'lastname' => str_repeat('b', 100)];
        
        try {
            include __DIR__ . '/../src/student_history_view.php';
        } catch (\Exception $e) {
            // Catch any database errors from oversized strings
        }
        $output = ob_get_clean();

        // Form should still render even if query fails
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with whitespace-only names
     */
    public function test_page_with_whitespace_only_names() {
        ob_start();
        
        $_GET = ['firstname' => '   ', 'lastname' => '   '];
        
        include __DIR__ . '/../src/student_history_view.php';
        $output = ob_get_clean();

        // Should still render (isset returns true for whitespace strings)
        $this->assertStringContainsString('<form', $output);
    }
}