<?php

require_once __DIR__ . '/../src/setup_tools.php';
require_once __DIR__ . '/../src/display_table_tools.php';

use PHPUnit\Framework\TestCase;

// !! TESTS BELOW GENERATED BY COPILOT !!

class student_schedule_viewTest extends TestCase
{
    private $conn;

    protected function setUp(): void {
        $this->conn = config();
    }

    protected function tearDown(): void {
        if ($this->conn) {
            $this->conn->close();
        }
    }

    /**
     * Test that the page renders the form HTML without errors
     */
    public function test_page_renders_form() {
        ob_start();
        
        // Simulate no GET parameters
        $_GET = [];
        
        // Include the page and capture output
        include __DIR__ . '/../src/student_schedule_view.php';
        $output = ob_get_clean();

        // Assert the form sections are present
        $this->assertStringContainsString('<form action="student_schedule_view.php" method="GET">', $output);
        $this->assertStringContainsString('Select a Student:', $output);
        $this->assertStringContainsString('Select a Subject or Class:', $output);
        $this->assertStringContainsString('Select a Term:', $output);
        $this->assertStringContainsString('<input type="submit" value="See Details"/>', $output);
    }

    /**
     * Test page with no GET parameters (should show all schedules)
     */
    public function test_page_with_no_parameters() {
        ob_start();
        
        $_GET = [];
        
        include __DIR__ . '/../src/student_schedule_view.php';
        $output = ob_get_clean();

        // Should still render the form and table structure
        $this->assertStringContainsString('<form', $output);
        $this->assertStringContainsString('</form>', $output);
    }

    /**
     * Test page with student info only
     */
    public function test_page_with_student_info_only() {
        ob_start();
        
        $_GET = ['firstname' => 'John', 'lastname' => 'Doe'];
        
        include __DIR__ . '/../src/student_schedule_view.php';
        $output = ob_get_clean();

        // Should render form and table
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with subject code only
     */
    public function test_page_with_subject_code_only() {
        ob_start();
        
        $_GET = ['subjectcode' => 'CSC'];
        
        include __DIR__ . '/../src/student_schedule_view.php';
        $output = ob_get_clean();

        // Should render form
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with subject and class number
     */
    public function test_page_with_subject_and_class() {
        ob_start();
        
        $_GET = ['subjectcode' => 'CSC', 'classnumber' => '110'];
        
        include __DIR__ . '/../src/student_schedule_view.php';
        $output = ob_get_clean();

        // Should render form and table
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with term info only
     */
    public function test_page_with_term_only() {
        ob_start();
        
        $_GET = ['term' => 'SP'];
        
        include __DIR__ . '/../src/student_schedule_view.php';
        $output = ob_get_clean();

        // Should render form
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with term and year
     */
    public function test_page_with_term_and_year() {
        ob_start();
        
        $_GET = ['term' => 'FA', 'tyear' => '2025'];
        
        include __DIR__ . '/../src/student_schedule_view.php';
        $output = ob_get_clean();

        // Should render form and table
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with all parameters filled
     */
    public function test_page_with_all_parameters() {
        ob_start();
        
        $_GET = [
            'firstname' => 'John',
            'lastname' => 'Doe',
            'subjectcode' => 'CSC',
            'classnumber' => '110',
            'term' => 'FA',
            'tyear' => '2025'
        ];
        
        include __DIR__ . '/../src/student_schedule_view.php';
        $output = ob_get_clean();

        // Should render form and table
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with special characters in firstname (XSS prevention)
     */
    public function test_page_with_special_characters_in_firstname() {
        ob_start();
        
        $_GET = ['firstname' => '<script>', 'lastname' => 'Test'];
        
        try {
            include __DIR__ . '/../src/student_schedule_view.php';
        } catch (\Exception $e) {
            // Catch any exceptions and clean buffer
        }
        $output = ob_get_clean();

        // Should sanitize and render safely
        $this->assertStringNotContainsString('<script>', $output);
        // Form should still be present
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with special characters in lastname
     */
    public function test_page_with_special_characters_in_lastname() {
        ob_start();
        
        $_GET = ['firstname' => 'Test', 'lastname' => '<script>'];
        
        try {
            include __DIR__ . '/../src/student_schedule_view.php';
        } catch (\Exception $e) {
            // Catch any exceptions and clean buffer
        }
        $output = ob_get_clean();

        // Should sanitize and render safely
        $this->assertStringNotContainsString('<script>', $output);
        // Form should still be present
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with special characters in subject code
     */
    public function test_page_with_special_characters_in_subject() {
        ob_start();
        
        $_GET = ['subjectcode' => '<script>'];
        
        try {
            include __DIR__ . '/../src/student_schedule_view.php';
        } catch (\Exception $e) {
            // Catch any exceptions and clean buffer
        }
        $output = ob_get_clean();

        // Should sanitize and render safely
        $this->assertStringNotContainsString('<script>', $output);
        // Form should still be present
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with empty firstname but filled lastname (should require both)
     */
    public function test_page_with_empty_firstname() {
        ob_start();
        
        $_GET = ['firstname' => '', 'lastname' => 'Doe'];
        
        include __DIR__ . '/../src/student_schedule_view.php';
        $output = ob_get_clean();

        // Should render form (empty string fails !empty check)
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with empty lastname but filled firstname (should require both)
     */
    public function test_page_with_empty_lastname() {
        ob_start();
        
        $_GET = ['firstname' => 'John', 'lastname' => ''];
        
        include __DIR__ . '/../src/student_schedule_view.php';
        $output = ob_get_clean();

        // Should render form (empty string fails !empty check)
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with empty subject code
     */
    public function test_page_with_empty_subject_code() {
        ob_start();
        
        $_GET = ['subjectcode' => ''];
        
        include __DIR__ . '/../src/student_schedule_view.php';
        $output = ob_get_clean();

        // Should render form (empty string fails !empty check)
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with empty term but filled year
     */
    public function test_page_with_empty_term() {
        ob_start();
        
        $_GET = ['term' => '', 'tyear' => '2025'];
        
        include __DIR__ . '/../src/student_schedule_view.php';
        $output = ob_get_clean();

        // Should render form (empty string fails !empty check)
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with empty year but filled term
     */
    public function test_page_with_empty_year() {
        ob_start();
        
        $_GET = ['term' => 'FA', 'tyear' => ''];
        
        include __DIR__ . '/../src/student_schedule_view.php';
        $output = ob_get_clean();

        // Should render form (empty string fails !empty check)
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test all form input field names are present
     */
    public function test_form_input_field_names() {
        ob_start();
        
        $_GET = [];
        
        include __DIR__ . '/../src/student_schedule_view.php';
        $output = ob_get_clean();

        // Check for correct input field names
        $this->assertStringContainsString('name="firstname"', $output);
        $this->assertStringContainsString('name="lastname"', $output);
        $this->assertStringContainsString('name="subjectcode"', $output);
        $this->assertStringContainsString('name="classnumber"', $output);
        $this->assertStringContainsString('name="term"', $output);
        $this->assertStringContainsString('name="tyear"', $output);
    }

    /**
     * Test form method is GET
     */
    public function test_form_method_is_get() {
        ob_start();
        
        $_GET = [];
        
        include __DIR__ . '/../src/student_schedule_view.php';
        $output = ob_get_clean();

        // Check for GET method
        $this->assertStringContainsString('method="GET"', $output);
    }

    /**
     * Test page with numeric year value
     */
    public function test_page_with_numeric_year() {
        ob_start();
        
        $_GET = ['term' => 'SP', 'tyear' => '2021'];
        
        include __DIR__ . '/../src/student_schedule_view.php';
        $output = ob_get_clean();

        // Should render form
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with non-numeric year (type coercion)
     */
    public function test_page_with_non_numeric_year() {
        ob_start();
        
        $_GET = ['term' => 'FA', 'tyear' => 'abc'];
        
        try {
            include __DIR__ . '/../src/student_schedule_view.php';
        } catch (\Exception $e) {
            // Catch any exceptions
        }
        $output = ob_get_clean();

        // Should still render form (htmlspecialchars handles it)
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with very long firstname
     */
    public function test_page_with_very_long_firstname() {
        ob_start();
        
        $_GET = ['firstname' => str_repeat('a', 100), 'lastname' => 'Test'];
        
        try {
            include __DIR__ . '/../src/student_schedule_view.php';
        } catch (\Exception $e) {
            // Catch any database errors
        }
        $output = ob_get_clean();

        // Form should still render
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with whitespace-only firstname and lastname
     */
    public function test_page_with_whitespace_only_names() {
        ob_start();
        
        $_GET = ['firstname' => '   ', 'lastname' => '   '];
        
        include __DIR__ . '/../src/student_schedule_view.php';
        $output = ob_get_clean();

        // Should still render (isset returns true, !empty returns true for whitespace)
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test that classnumber is only used when subjectcode is set
     */
    public function test_classnumber_without_subject() {
        ob_start();
        
        $_GET = ['classnumber' => '110']; // classnumber without subject
        
        include __DIR__ . '/../src/student_schedule_view.php';
        $output = ob_get_clean();

        // Should still render (classnumber is ignored without subject)
        $this->assertStringContainsString('<form', $output);
    }

    /**
     * Test page with abbreviated term codes
     */
    public function test_page_with_term_abbreviations() {
        ob_start();
        
        $_GET = ['term' => 'SP', 'tyear' => '2025'];
        
        include __DIR__ . '/../src/student_schedule_view.php';
        $output = ob_get_clean();

        // Should render form
        $this->assertStringContainsString('<form', $output);
    }
}