<?php
//GENERATED BY COPILOT
require_once __DIR__ . '/../src/setup_tools.php'; 
require_once __DIR__ . '/../src/display_adding_tools.php';
require_once __DIR__ . '/../src/display_table_tools.php';
require_once __DIR__ . '/../src/alter_tools.php';
use PHPUnit\Framework\TestCase;


class ViewEditsTest extends TestCase
{
    private $conn;

protected function setUp(): void
{
    $this->conn = config();
    $this->conn->begin_transaction(); // Start a transaction
}

protected function tearDown(): void
{
    if ($this->conn) {
        $this->conn->rollback(); // Undo any inserts, updates, deletes
        $this->conn->close();
    }
}
 

  

    /** @test */
    public function it_soft_deletes_slot_without_html_pollution()
    {
        // Pick a real slot_id
        $res = $this->conn->query("SELECT slot_id FROM slots LIMIT 1");
        $row = $res->fetch_assoc();
        $slotId = $row['slot_id'];

        // Simulate POST
        $_POST = ['delbtn' => true, 'checkbox0' => true];
        $result = $this->conn->query("SELECT slot_id FROM slots WHERE slot_id = $slotId");

        // Suppress HTML output
        ob_start();
        view_edits($this->conn, $result, 1);
        ob_end_clean(); // discard whatever was printed

        // Assert DB change
        $check = $this->conn->query("SELECT deleted_when FROM slots WHERE slot_id = $slotId");
        $updated = $check->fetch_assoc();

        $this->assertNotNull($updated['deleted_when'], "Slot should be soft deleted");
    }

    /** @test */
    public function it_soft_deletes_tutor_without_html_pollution()
    {
        $res = $this->conn->query("SELECT tutor_id AS `Student ID` FROM tutors LIMIT 1");
        $row = $res->fetch_assoc();
        $tutorId = $row['Student ID'];

        $_POST = ['delbtn' => true, 'checkbox0' => true];
        $result = $this->conn->query("SELECT tutor_id AS `Student ID` FROM tutors WHERE tutor_id = $tutorId");

        ob_start();
        view_edits($this->conn, $result, 2);
        ob_end_clean();

        $check = $this->conn->query("SELECT deleted_when FROM tutors WHERE tutor_id = $tutorId");
        $updated = $check->fetch_assoc();

        $this->assertNotNull($updated['deleted_when'], "Tutor should be soft deleted");
    }
}