<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'add_toolstest' => '/../test/add_toolsTest.php',
                'alter_toolstest' => '/../test/alter_toolsTest.php',
                'calendar_viewtest' => '/../test/calendar_viewTest.php',
                'delete_toolstest' => '/../test/delete_toolsTest.php',
                'display_database_toolstest' => '/../test/display_database_toolsTest.php',
                'display_table_toolstest' => '/../test/display_table_toolsTest.php',
                'full_schedule_viewtest' => '/../test/full_schedule_viewTest.php',
                'index_logintest' => '/../test/index_loginTest.php',
                'student_history_viewtest' => '/../test/student_history_viewTest.php',
                'student_schedule_viewtest' => '/../test/student_schedule_viewTest.php',
                'vieweditstest' => '/../test/ViewEditsTest.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd


// ADDITION FROM COPILOT
// Start output buffering during test bootstrap so headers() can be sent
// later in code without causing "headers already sent" warnings.
if (!ob_get_level()) {
    // Start an output buffer so header() calls later won't fail with "headers
    // already sent". Tests should use their own ob_start()/ob_get_clean() to
    // capture output; any buffers left open will be cleaned at shutdown.
    ob_start();
    register_shutdown_function(function () {
        while (ob_get_level()) {
            @ob_end_clean();
        }
    });
}
